sudo: true
language: node_js
node_js:
  - '10'

branches:
  only:
    - /.*/

# Keep the npm cache around to speed up installs
cache:
  npm: true
  directories:
    - '$HOME/.npm'

install:
  - yarn install --production=false

before_script:
  - yarn bootstrap

script:
  - yarn lint
  - yarn build
  - yarn test

notifications:
  email:
    on_failure: always
